### ISSUE TITLE
color customize? cant read headers

### ISSUE THREAD

**Issue by zeltak** [algernon/elfeed-goodies#5]
Hi

Thx so much for working on this, these are 2 things that i myself have requested from the elfeed dev :)

one thing is the colors. on the theme i use (leuven) the colors are way off and unreadable. can they be customized?

thx so much

z

**Comment by algernon** [comment]
All faces used by the package are customisable, either through `M-x customize-group elfeed` or `M-x customize-group elfeed-goodies`, or `M-x customize-group powerline`, depending on which face you want to change.

I'm not sure how convenient that is, or how `M-x customize-group elfeed-goodies` is presented, because I didn't get as far as making sure it looks ok. I just implemented the code part, without verifying.

Can you check whether customising the faces works for you?

**Comment by algernon** [comment]
Mkay, I had a look at the elfeed-goodies customise group, and the faces ain't there. I'll see if I can fix that.

**Comment by algernon** [comment]
The reasons faces aren't in the `M-x customize-group elfeed-goodies` set, is because elfeed goodies itself does not define any new faces. It uses faces from `elfeed`, mostly.

I just checked the faces with the leuven theme, and they indeed, are undreadable.

**Comment by RKBK** [comment]
I'm using the leuven theme, and while the standard elfeed works just fine for me (i.e. I actually can read everything), elfeed-goodies is unreadable. Has something changed so that elfeed now is usable with leuven, but elfeed-goodies still isn't?

**Comment by fshapps** [comment]
Same here. Using adwaita theme. Elfeed is fine. Most of Elfeed-goodies is fine, too. Only exception is the elfeed-entry "Subject" field. The text is dark black on a black background. A simple fix would be to make that text white like in the other fields. See attached screenshot.
![elfeed](https://user-images.githubusercontent.com/4127972/39674152-a408f36e-5115-11e8-8508-7c26ec3dcf84.jpg)

**Comment by fshapps** [comment]
Just noticed this issue is closed. Will open a new one.
